name: Generate Contributors Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # 建议加上这个，这样你可以在 Actions 页面手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Generate Contributors SVG
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|dependabot\[bot\]|github-actions\[bot\])
          avatarSize: 42
          output: contributors.svg
          commit-message: "chore: update contributors.svg"
