name: Generate Contributors Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 

      - name: Generate Contributors SVG
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|dependabot\[bot\]|github-actions\[bot\])
          avatarSize: 42
          output: contributors.svg

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update contributors.svg"
          file_pattern: 'contributors.svg'
